# Generated by Django 3.0.8 on 2020-07-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Funcionario',
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários')], max_length=12, verbose_name='Icone'),
        ),
    ]
