# Generated by Django 3.0.8 on 2020-07-23 02:44

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200722_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design')], max_length=12, verbose_name='Icone'),
        ),
    ]
