# Generated by Django 3.0.8 on 2020-07-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200722_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile')], max_length=12, verbose_name='Icone'),
        ),
    ]
