# Generated by Django 3.0.8 on 2020-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('dnasc', models.DateField(verbose_name='Data de nacimento')),
                ('email', models.EmailField(max_length=100)),
                ('typeteste', models.CharField(choices=[('ertpcr', 'ERT-PCR'), ('sorologia', 'ERT-PCR'), ('testerapidoatg', 'Teste Rápido - Antígenos'), ('testerapidoatc', 'Teste Rápido - Anticorpos')], max_length=100, verbose_name='Tipo do teste')),
                ('resteste', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=100, verbose_name='Resultado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
